src/Entity/Contributions.php
<?php

namespace App\Entity;

use App\Repository\ContributionsRepository;
use App\Entity\Categoryfinances;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ContributionsRepository::class)]
class Contributions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 10)]
    private $tid;

    /**
     * @Assert\GreaterThanOrEqual(50)
     * @Assert\LessThanOrEqual(500)
     */
    #[ORM\Column(type: 'string', length: 10)]
    private $amount;

    #[ORM\Column(type: 'string', length: 50)]
    private $period;

    #[ORM\Column(type: 'string', length: 50)]
    private $status;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $validated_at;

    #[ORM\Column(type: 'string', length: 10, nullable: true)]
    private $validatedby;

     /**
     * @Assert\NotEqualTo("0",
     * message="Merci de selectionner un mode de paIement.")
     */
    #[ORM\Column(type: 'string', length: 50)]
    private $paymentmode;

    #[ORM\Column(type: 'string', length: 255)]
    private $proof;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: 'contributions')]
    private $Users;

   
    #[ORM\Column(type: 'string', length: 10)]
    private $createdby;

    #[ORM\Column(type: 'string', length: 10)]
    private $createdmonth;

    #[ORM\Column(type: 'string', length: 10)]
    private $createdyear;

    #[ORM\Column(type: 'string', length: 10)]
    private $catfinance;

    #[ORM\Column(type: 'string', length: 10)]
    private $paidforhowmanymonth;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTid(): ?string
    {
        return $this->tid;
    }

    public function setTid(string $tid): self
    {
        $this->tid = $tid;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(string $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getValidatedAt(): ?\DateTimeInterface
    {
        return $this->validated_at;
    }

    public function setValidatedAt(\DateTimeInterface $validated_at): self
    {
        $this->validated_at = $validated_at;

        return $this;
    }

    public function getValidatedby(): ?string
    {
        return $this->validatedby;
    }

    public function setValidatedby(?string $validatedby): self
    {
        $this->validatedby = $validatedby;

        return $this;
    }

    public function getPaymentmode(): ?string
    {
        return $this->paymentmode;
    }

    public function setPaymentmode(?string $paymentmode): self
    {
        $this->paymentmode = $paymentmode;

        return $this;
    }

    public function getProof(): ?string
    {
        return $this->proof;
    }

    public function setProof(string $proof): self
    {
        $this->proof = $proof;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->Users;
    }

    public function setUsers(?Users $Users): self
    {
        $this->Users = $Users;

        return $this;
    }

    
    public function getCreatedby(): ?string
    {
        return $this->createdby;
    }

    public function setCreatedby(string $createdby): self
    {
        $this->createdby = $createdby;

        return $this;
    }

    
    public function getCreatedmonth(): ?string
    {
        return $this->createdmonth;
    }

    public function setCreatedmonth(string $createdmonth): self
    {
        $this->createdmonth = $createdmonth;

        return $this;
    }

    public function getCreatedyear(): ?string
    {
        return $this->createdyear;
    }

    public function setCreatedyear(string $createdyear): self
    {
        $this->createdyear = $createdyear;

        return $this;
    }

    public function getCatfinance(): ?string
    {
        return $this->catfinance;
    }

    public function setCatfinance(string $catfinance): self
    {
        $this->catfinance = $catfinance;

        return $this;
    }

    public function getPaidforhowmanymonth(): ?string
    {
        return $this->paidforhowmanymonth;
    }

    public function setPaidforhowmanymonth(string $paidforhowmanymonth): self
    {
        $this->paidforhowmanymonth = $paidforhowmanymonth;

        return $this;
    }

    

    
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
#[ORM\Entity(repositoryClass: UsersRepository::class)]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 10)]
    private $approverlevel;

    /**
     * @Assert\Email(
     *     message = "L'email '{{ value }}' n'est pas valide."
     * )
     */
    #[ORM\Column(type: 'string', length: 100)]
    private $email;

    #[ORM\Column(type: 'string', length: 10)]
    private $matricule;

    #[ORM\Column(type: 'boolean')]
    private $isactive;

    /**
     * @Assert\Length(
     *      min = 3,
     *      max = 20,
     *      minMessage = "Le Prénom devra contenir au moins {{ limit }} caractères",
     *      maxMessage = "Le Prénom ne peut depasser {{ limit }} caractères"
     * )
     */
    #[ORM\Column(type: 'string', length: 100)]
    private $fname;
    /**
     * @Assert\Length(
     *      min = 3,
     *      max = 20,
     *      minMessage = "Le Nom devra contenir au moins {{ limit }} caractères",
     *      maxMessage = "Le Nom ne peut depasser {{ limit }} caractères"
     * )
     */
    #[ORM\Column(type: 'string', length: 100)]
    private $lname;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'Users', targetEntity: Contributions::class)]
    private $contributions;

    #[ORM\Column(type: 'string', length: 255)]
    private $avatar;

    public function __construct()
    {
        $this->contributions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getApproverlevel(): ?string
    {
        return $this->approverlevel;
    }

    public function setApproverlevel(string $approverlevel): self
    {
        $this->approverlevel = $approverlevel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getIsactive(): ?bool
    {
        return $this->isactive;
    }

    public function setIsactive(bool $isactive): self
    {
        $this->isactive = $isactive;

        return $this;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    
    

    /**
     * @return Collection|Contributions[]
     */
    public function getContributions(): Collection
    {
        return $this->contributions;
    }

    public function addContribution(Contributions $contribution): self
    {
        if (!$this->contributions->contains($contribution)) {
            $this->contributions[] = $contribution;
            $contribution->setUsers($this);
        }

        return $this;
    }

    public function removeContribution(Contributions $contribution): self
    {
        if ($this->contributions->removeElement($contribution)) {
            // set the owning side to null (unless already changed)
            if ($contribution->getUsers() === $this) {
                $contribution->setUsers(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    
}

templates/finance/addContrib.html.twig
{% extends 'template.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
    {% for flashError in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}


    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
       <div class="container-fluid">
        <div class="row">
            
          <!-- left column -->
          <div class="col-md-6 offset-3 mx-auto">
                            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title" id="membre">Ajouter Contribution </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              
                <div class="card-body">
                {{ form_start(contribForm) }}
                <div class="col">{{ form_row(contribForm.users, {'id': 'nomMembre', 'attr': { 'onChange': 'getMembre()', 'onClick': 'membreChange()'}})}}</div>
                <div class="col">{{ form_row(contribForm.amount,{
                  label: 'Montant'
                  }) }}</div>
                
                <div class="col">{{ form_row(contribForm.period,{
                  label: 'Période'
                  }) }}</div>
                <div class="col">{{ form_row(contribForm.paymentmode, {
                    label: 'Mode de Paiement'
                }) }}</div>
                
                <div class="col">{{ form_row(contribForm.proof) }}</div>
      </div>

            <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
               {{ form_end(contribForm) }}
            </div>
           </div>
           </div>
           </div> 
      

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

{# <!-- une contribution de 100 - Period à entrer est [1,2021 Debut de dette],1;-->
<!--150, 2-->
<!--50, 0-->
<!--200, 3-->#}

templates/finance/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Financial Health 2022</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
                <div class="row">
                  <div class="col-6 col-md-3 text-center">
                    <input type="text" class="knob" value="{{trackRevenue}}" data-thickness="0.1" data-width="90" data-height="90"
                           data-fgColor="#3c8dbc" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button" data-tooltip="tooltip" title="Budget 2022: ${{budget}} | YTD: ${{revenue}}">

                    <div class="knob-label">Incomes Tracker</div>
                  </div>
                  <!-- ./col -->
                  <div class="col-6 col-md-3 text-center">
                    <input type="text" class="knob" value="{{trackForecast}}" data-thickness="0.1" data-width="90" data-height="90"
                           data-fgColor="#f56954" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button" data-tooltip="tooltip" title="Budget 2022: ${{budget}} | YTD: ${{forecast}}">
                    <div class="knob-label">YTD Forecast</div>
                  </div>
                  <!-- ./col -->
                  <div class="col-6 col-md-3 text-center">
                    <input type="text" class="knob" value="60" data-thickness="0.1" data-width="90" data-height="90"
                           data-fgColor="#00a65a">

                    <div class="knob-label">Expenses vs Budget</div>
                  </div>
                  <!-- ./col -->
                  <div class="col-6 col-md-3 text-center">
                    <input type="text" class="knob" value="10" data-thickness="0.1" data-width="90" data-height="90"
                           data-fgColor="#00c0ef">

                    <div class="knob-label">Zero RaP</div>
                  </div>
                  <!-- ./col -->
                </div>
                <!-- /.row -->
              </div>
              <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

 <div class="row">
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header border-0">
                <div class="d-flex justify-content-between">
                  <h3 class="card-title">Contributions View</h3>
                  <div class="card-tools">
                  <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                  </a>
                </div>
                </div>
              </div>
              <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$4,250.00</span>
                    <span>CoT - Contrbutions Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-success">
                      <i class="fas fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Month on Month</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fas fa-square text-primary"></i> 2021
                  </span>

                  <span>
                    <i class="fas fa-square text-gray"></i> 2020
                  </span>
                </div>
              </div>
            </div>
            <!-- /.card -->

          
          </div>
          <!-- /.col-md-6 -->
           <div class="col-lg-6">
            <div class="card">
              <div class="card-header border-0">
                <div class="d-flex justify-content-between">
                  <h3 class="card-title">Late Insights</h3>
                  <a href="#" class="btn btn-tool btn-sm">
                    <i class="fas fa-download"></i>
                  </a>
                </div>
              </div>
              <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$820.00</span>
                    <span>RoT - RaP Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-danger">
                      <i class="fas fa-arrow-down"></i> 12.5%
                    </span>
                    <span class="text-muted">MoM</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="visitors-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fas fa-square text-primary"></i> 2021
                  </span>

                  <span>
                    <i class="fas fa-square text-danger"></i> 2020
                  </span>
                </div>
              </div>
            </div>
            <!-- /.card -->
           
   
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->

          <!--.col-md-12 LISTING THE CONTRIBUTIONS TO BE VALIDATED-->
          

          <!-- Default box -->
      <div class="col-lg-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Contribution Validator</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
                <table class="table table-striped table-valign-middle">
                  <thead>
                  <tr>
                 
                    <th>#</th>
                    <th>Contributeur </th>
                    <th>Montant</th>
                    <th>Periode</th>
                    <th>Soumis le</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                   {% if pendingContribs %}
                   {% for pendingContrib in pendingContribs %}
                  <tr>
                    <td>{{pendingContrib.tid}}</td>
                    <td>{{pendingContrib.users.fname}} {{pendingContrib.users.lname}}</td>
                    <td>{{pendingContrib.amount |format_currency('USD', {rounding_mode: 'floor'})}}</td>
                    <td>{{pendingContrib.period}}</td>
                    <td>{{pendingContrib.createdAt |date("m/d/Y")}}</td>
                    <td>
                    {% if pendingContrib.status == '0'%}
                    <a href="{{path('finance_hand', {'user_id': pendingContrib.users.id})}}"><center><i class="far fa-hand-paper"></i></center></a>
                    
                    {% else %}
                        <center>
                    <a href="{{path('finance_validate', {'user_id': pendingContrib.users.id})}}" data-toggle="modal" data-target="#exampleModal"><img src="{{asset("dist/img/edit.png")}}" alt="Edit Icon" width='20' height='20' ></a>
                    
                     <a href="{{asset("uploads/proof/"~ pendingContrib.proof)}}" target="blank"><img src="{{asset("dist/img/search.png")}}" alt="Edit Icon" width='20' height='20' ></a></center>
                    {% endif %}
                    </td>
                    
                  </tr>
                
                   {% endfor %}
                   {% else %}
                     <tr>
                   <td colspan="6" style='text-align:center; vertical-align:middle'>Aucune contribution à valider.  </td>
                   </tr>
                      {% endif %}
                   
                  </tbody>
                </table>
                <!-- /.row -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <a href="{{path('finance_add_contribution')}}" class="btn btn-info btn-flat btn-sm">Contribution pour Tiers</a>
              </div>
        <!-- /.card-footer-->
      </div></div>
            <!-- /.card -->
          </div>
        </div>
        
        <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Validation Contribution</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  <div class="modal-body">
  <center>
   {% if pendingContribs %}
  {% for pendingContrib in pendingContribs %}
  <form method='get' action='validate/{{pendingContrib.users.id}}'> 
  {% endfor %}{% endif %} 
  <div class="form-check">
  <input class="form-check-input" type="radio" name="RadioValidation" id="radioValidate" value="on">
  <label class="form-check-label" for="radioValidate">
    Approuver 
  </label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <input class="form-check-input" type="radio" name="RadioValidation" id="radioRejete" value="off">
  <label class="form-check-label" for="radioRejete">
  Rejeter
  </label>
</div>

</center>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Valider</button>
      </div>
    </div>
    </form>  
  </div>
</div>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}